[workspace]
name = "ispy2-r2r"
authors = [
    "Katy Scott <bhklab.katyscott@gmail.com>",
    "Nasim BondarSahebi <bhklab.nasimbondarsahebi@gmail.com>"
]
description = "Running READII-2-ROQC on ISPY2"
license = "MIT"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]

[environments]
quality = { features = ["quality"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }

[activation]
env.CONFIG = "${PIXI_PROJECT_ROOT}/config"
env.METADATA = "${PIXI_PROJECT_ROOT}/metadata"
env.LOGS = "${PIXI_PROJECT_ROOT}/logs"
env.RAWDATA = "${PIXI_PROJECT_ROOT}/data/rawdata"
env.PROCDATA = "${PIXI_PROJECT_ROOT}/data/procdata"
env.RESULTS = "${PIXI_PROJECT_ROOT}/data/results"
env.SCRIPTS = "${PIXI_PROJECT_ROOT}/workflow/scripts"

[dependencies]
python = "==3.12"
ipython = ">=9.3.0,<10"
ipykernel = ">=6.29.5,<7"
jupyterlab = ">=4.4.3,<5"
pip = ">=25.1.1,<26"
r-base = ">=4.4.2,<4.5"
r-rmarkdown = ">=2.29,<3"
r-knitr = ">=1.50,<2"
snakemake = ">=9.6.0,<10"

[pypi-dependencies]
med-imagetools = ">=2.10.0, <3"
readii = ">=1.36.2, <2"
damply = ">=0.17.0, <0.18"
highdicom = ">=0.25.1, <0.26"

[tasks]
example_script = { cmd = "python $SCRIPTS/run_feature_extraction.py" }

[tasks.make_kernel]
cmd = "python -m ipykernel install --user --name=ispy2-r2r --display-name 'Python (ispy2-r2r)'"
description = "Register the ispy2-r2r environment as a Jupyter kernel"

############################################## QUALITY ###############################################

[feature.quality.dependencies]
ruff = "*"

[feature.quality.tasks]
ruff-check.cmd = ["ruff", "check"]
ruff-check.inputs = ["config/ruff.toml", "workflow"]
ruff-check.description = "Run ruff check"

ruff-format.cmd = ["ruff", "format"]
ruff-format.inputs = ["config/ruff.toml", "workflow"]
ruff-format.depends-on = ["ruff-check"]
ruff-format.description = "Run ruff format, run check first"

qc.depends-on = ["ruff-format", "ruff-check"]
qc.description = "Quality check: ruff check and format"

############################################## DOCS ################################################

[feature.docs.dependencies]
mkdocs = "*"
mkdocs-include-markdown-plugin = ">=7.0.0,<8"

[feature.docs.tasks.doc-build]
cmd = "mkdocs build -f mkdocs.yaml"
inputs = ["docs"]
outputs = ["site"]
description = "Build documentation with mkdocs"

[feature.docs.tasks.doc-serve]
cmd = "mkdocs serve -f mkdocs.yaml"
depends-on = ["doc-build"]
inputs = ["docs"]
description = "Serve documentation with mkdocs, runs doc-build first"


