[workspace]
name = "ispy2-r2r"
authors = [
    "Katy Scott <bhklab.katyscott@gmail.com>",
    "Nasim BondarSahebi <bhklab.nasimbondarsahebi@gmail.com>"
]
description = "Running READII-2-ROQC on ISPY2"
license = "MIT"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]

[environments]
quality = { features = ["quality"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }

[activation]
env.CONFIG = "${PIXI_PROJECT_ROOT}/config"
env.METADATA = "${PIXI_PROJECT_ROOT}/metadata"
env.LOGS = "${PIXI_PROJECT_ROOT}/logs"
env.RAWDATA = "${PIXI_PROJECT_ROOT}/data/rawdata"
env.PROCDATA = "${PIXI_PROJECT_ROOT}/data/procdata"
env.RESULTS = "${PIXI_PROJECT_ROOT}/data/results"
env.SCRIPTS = "${PIXI_PROJECT_ROOT}/workflow/scripts"

[dependencies]
python = "3.10.*"
ipython = "*"
ipykernel = ">=6.29.5,<7"
jupyterlab = ">=4.4.2,<5"
pip = "*"
pytz = ">=2025.2,<2026"
jupyter = ">=1.1.1,<2"
jupyter_client = ">=8.6.3,<9"
pandas = "*"
dcm2niix = ">=1.0.20241211,<2"
boost-cpp = "==1.78.0"
libblas = ">=3.9.0,<4.0a0"
liblapack = ">=3.9.0,<4"
zlib = ">=1.3.1,<2"
fslpy = ">=3.21.1,<4"
hdf5 = "==1.14.4"
h5py = ">=3.10.0"
matplotlib = ">=3.9.0,<4"
simpleitk = ">=2.4.1,<3"



[pypi-dependencies]
# problem: med-imagetools==1.10.1 depends on numpy>=1.26.4,<2  but another dependency is forcing numpy==2.2.6
#med-imagetools = "==1.10.1" or "*" not working
#pandas = "==2.2.3"

readii = ">=1.36.2,<2"
scikit-image = "==0.24.0"
pyradiomics-bhklab = "==3.1.4"
sqlalchemy = "==2.0.36"
sqlitedict = "==2.1.0"
rich = "==13.9.4"
tqdm = "==4.67.1"
pydicom = ">=2.3.1,<3"
imageio = "==2.36.1"
networkx = "==3.4.2"
pyyaml = "==6.0.2"
#med-imagetools = ">2"
med-imagetools = "==2.4.0" 
damply = "*"


[tasks]
example_script = { cmd = "python $SCRIPTS/run_feature_extraction.py" }

[tasks.make_kernel]
cmd = "python -m ipykernel install --user --name=ispy2-r2r --display-name 'Python (ispy2-r2r)'"
description = "Register the ispy2-r2r environment as a Jupyter kernel"

############################################## QUALITY ###############################################

[feature.quality.dependencies]
ruff = "*"

[feature.quality.tasks]
ruff-check.cmd = ["ruff", "check"]
ruff-check.inputs = ["config/ruff.toml", "workflow"]
ruff-check.description = "Run ruff check"

ruff-format.cmd = ["ruff", "format"]
ruff-format.inputs = ["config/ruff.toml", "workflow"]
ruff-format.depends-on = ["ruff-check"]
ruff-format.description = "Run ruff format, run check first"

qc.depends-on = ["ruff-format", "ruff-check"]
qc.description = "Quality check: ruff check and format"

############################################## DOCS ################################################

[feature.docs.dependencies]
mkdocs = "*"
mkdocs-include-markdown-plugin = ">=7.0.0,<8"

[feature.docs.tasks.doc-build]
cmd = "mkdocs build -f mkdocs.yaml"
inputs = ["docs"]
outputs = ["site"]
description = "Build documentation with mkdocs"

[feature.docs.tasks.doc-serve]
cmd = "mkdocs serve -f mkdocs.yaml"
depends-on = ["doc-build"]
inputs = ["docs"]
description = "Serve documentation with mkdocs, runs doc-build first"
