DATA_SOURCE: "TCIA"
DATASET_NAME: "ISPY2"

### CLINICAL VARIABLE INFORMATION ###
CLINICAL:
    FILE: ""
    OUTCOME_VARIABLES:
        time_label: "overall_survival_in_days"
        event_label: "event_overall_survival"
        convert_to_years: True
        event_value_mapping: {} # Event values should be in the order {0: Alive_value, 1: Dead_value}
    EXCLUSION_VARIABLES: {}

### MED-IMAGETOOLS settings
MIT:
    ROI_MATCH_MAP:
      Tumor:VOLSER_Analysis_Mask 
    ROI_STRATEGY: MERGE
    MODALITIES: 
      image: MR
      mask: SEG

### READII settings
READII:
    IMAGE_TYPES:
        regions:
            - "full"
        permutations:
            - "shuffled"
        crop:
    TRAIN_TEST_SPLIT:
        split: False
        split_variable: {}
        impute: null

RANDOM_SEED: 10
